# Generated by Django 3.2.6 on 2021-08-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentid',
            field=models.CharField(max_length=64, unique=True, verbose_name='학번'),
        ),
    ]
