# Generated by Django 3.2.6 on 2021-09-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_user_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_time',
            field=models.IntegerField(default=0, verbose_name='추가 시간'),
            preserve_default=False,
        ),
    ]
