# Generated by Django 3.2.6 on 2021-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_user_extra_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=512, verbose_name='비밀번호'),
        ),
    ]
