# Generated by Django 3.2.6 on 2021-09-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210911_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=512)),
                ('date', models.DateTimeField(verbose_name='날짜/시간')),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.activity')),
            ],
        ),
    ]
