# Generated by Django 3.2.6 on 2021-09-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='apply',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='milestone',
            new_name='title',
        ),
    ]
