# Generated by Django 3.2.6 on 2021-09-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210927_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='내용')),
                ('date', models.DateTimeField(verbose_name='날짜/시간')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.activity')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
