# Generated by Django 4.0.4 on 2022-05-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='활동명')),
                ('start_date', models.DateTimeField(verbose_name='신청 시작')),
                ('end_date', models.DateTimeField(verbose_name='신청 마감')),
                ('description', models.TextField(verbose_name='내용')),
                ('hour', models.IntegerField(verbose_name='부여하는 수과학 활동 시간')),
            ],
            options={
                'verbose_name': '활동',
                'verbose_name_plural': '활동',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=64, unique=True, verbose_name='학번')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('password', models.CharField(max_length=512, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생',
                'db_table': 'test_user',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='내용')),
                ('due_date', models.DateTimeField(verbose_name='날짜/시간')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.activity')),
            ],
            options={
                'verbose_name': '계획',
                'verbose_name_plural': '계획',
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='학번')),
                ('name', models.CharField(max_length=512)),
                ('reg_date', models.DateTimeField(verbose_name='date published')),
                ('state', models.IntegerField(choices=[(1, '신청'), (2, '취소'), (3, '승인'), (4, '이수')], default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.activity', verbose_name='활동')),
            ],
            options={
                'verbose_name': '승인',
                'verbose_name_plural': '승인',
            },
        ),
        migrations.CreateModel(
            name='Additonal_hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='사유')),
                ('extra_hour', models.IntegerField(default=0, verbose_name='추가 시간')),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.apply')),
            ],
            options={
                'verbose_name': '추가 시간',
                'verbose_name_plural': '추가 시간',
            },
        ),
    ]
