# Generated by Django 4.0.4 on 2022-05-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name': '신청', 'verbose_name_plural': '신청'},
        ),
    ]
