# Generated by Django 4.0.4 on 2022-05-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '활동', 'verbose_name_plural': '활동'},
        ),
        migrations.AlterModelOptions(
            name='additonal_hour',
            options={'verbose_name': '추가 시간', 'verbose_name_plural': '추가 시간'},
        ),
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name': '승인', 'verbose_name_plural': '승인'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': '계획', 'verbose_name_plural': '계획'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '학생', 'verbose_name_plural': '학생'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='test_user',
        ),
    ]
