# Generated by Django 3.2.6 on 2021-08-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_activity_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='state',
            field=models.IntegerField(choices=[(1, '신청'), (2, '취소'), (3, '승인'), (4, '완료')], default=1),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
