# Generated by Django 3.2.6 on 2021-08-24 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210819_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date to end'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date to start'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='state',
            field=models.IntegerField(choices=[(1, '신청'), (2, '취소'), (3, '승인'), (4, '이수')], default=1),
        ),
    ]
