# Generated by Django 3.2.6 on 2021-09-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(verbose_name='신청 마감'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='hour',
            field=models.IntegerField(verbose_name='부여하는 수과학 활동 시간'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(verbose_name='신청 시작'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=512, verbose_name='활동명'),
        ),
        migrations.CreateModel(
            name='Additonal_hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='사유')),
                ('extra_hour', models.IntegerField(default=0, verbose_name='추가 시간')),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.apply')),
            ],
        ),
    ]
