# Generated by Django 3.2.6 on 2021-09-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20210927_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='date',
            new_name='due_date',
        ),
    ]
