name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name : Create setting file
      run: |
        echo '{"Production":false,"SECRET_KEY":"x3^vralhx{6eGh,|UMsrjX=Gi*25k!Vt%4}*Yuyqgou8Z#!pwk","DEBUG":true,"ALLOWED_HOSTS":["127.0.0.1","192.168.0.53"]}' > jamsinhs/settings.json
    - name: Run Tests
      run: |
        python jamsinhs/manage.py test
